name: Main CI workflow

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  runs-build:
    name: Call Reuseable workflow
    uses: Benjakunee17/node-template/blob/main/.github/workflows/node.yml
    with:
      node-version: '20'