name: Main CI workflow
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  run-build:
    name: Call Reuseable workflow
    uses: Benjakunee17/node-template/.github/workflows/node.yml@main
    with:
      node-version: '20'